/*** 1. event_ingest table, using event_ingest.csv (including prelim set-up steps) ***/

create type hand_cd_type as enum('L', 'R');
create type battedball_cd_type as enum('F', 'L', 'P', 'G');
create type err_cd_type as enum('F', 'D', 'N', 'T');

create table fields (
  field_number integer not null,
  description varchar(43) not null,
  header varchar(25) not null
);

create table event_cd_desc (
  event_cd integer not null,
  description varchar(255) not null,
  abbreviation varchar(4) not null
);

create table event_ingest (
  event_uid varchar(15) primary key,
  game_id varchar(12) not null,
  game_date date not null,
  game_year integer not null,
  game_month integer not null,
  game_day_of_month integer not null,
  game_number integer not null,
  home_team_id varchar(3) not null,
  away_team_id varchar(3) not null,
  inn_ct integer not null,
  bat_home_id boolean not null,
  half_inning_id varchar(15) not null,
  outs_ct integer not null,
  balls_ct integer not null,
  strikes_ct integer not null,
  pitch_seq_tx varchar(255),
  away_score_ct integer not null,
  home_score_ct integer not null,
  runs integer not null,
  bat_id varchar(8) not null,
  bat_hand_cd hand_cd_type,
  resp_bat_id varchar(8) not null,
  resp_bat_hand_cd hand_cd_type,
  pit_id varchar(8) not null,
  pit_hand_cd hand_cd_type not null,
  resp_pit_id varchar(8) not null,
  resp_pit_hand_cd hand_cd_type not null,
  pos2_fld_id varchar(8) not null,
  pos3_fld_id varchar(8) not null,
  pos4_fld_id varchar(8) not null,
  pos5_fld_id varchar(8) not null,
  pos6_fld_id varchar(8) not null,
  pos7_fld_id varchar(8) not null,
  pos8_fld_id varchar(8) not null,
  pos9_fld_id varchar(8) not null,
  base1_run_id varchar(8),
  base2_run_id varchar(8),
  base3_run_id varchar(8),
  event_tx varchar(255) not null,
  leadoff_fl boolean not null,
  ph_fl boolean not null,
  bat_fld_cd integer not null,
  bat_lineup_id integer not null,
  event_cd integer not null,
  bat_event_fl boolean not null,
  ab_fl boolean not null,
  h_fl integer not null,
  sh_fl boolean not null,
  sf_fl boolean not null,
  event_outs_ct integer not null,
  dp_fl boolean not null,
  tp_fl boolean not null,
  rbi_ct integer not null,
  wp_fl boolean not null,
  pb_fl boolean not null,
  fld_cd integer not null,
  battedball_cd battedball_cd_type,
  bunt_fl boolean not null,
  foul_fl boolean not null,
  battedball_loc_tx varchar(255),
  err_ct integer not null,
  err1_fld_cd integer not null,
  err1_cd err_cd_type not null,
  err2_fld_cd integer not null,
  err2_cd err_cd_type not null,
  err3_fld_cd integer not null,
  err3_cd err_cd_type not null,
  bat_dest_id integer not null,
  run1_dest_id integer not null,
  run2_dest_id integer not null,
  run3_dest_id integer not null,
  runs_scored integer not null,
  bat_play_tx varchar(255),
  run1_play_tx varchar(255),
  run2_play_tx varchar(255),
  run3_play_tx varchar(255),
  run1_sb_fl boolean not null,
  run2_sb_fl boolean not null,
  run3_sb_fl boolean not null,
  run1_cs_fl boolean not null,
  run2_cs_fl boolean not null,
  run3_cs_fl boolean not null,
  run1_pk_fl boolean not null,
  run2_pk_fl boolean not null,
  run3_pk_fl boolean not null,
  run1_resp_pit_id varchar(8),
  run2_resp_pit_id varchar(8),
  run3_resp_pit_id varchar(8),
  game_new_fl boolean not null,
  game_end_fl boolean not null,
  pr_run1_fl boolean not null,
  pr_run2_fl boolean not null,
  pr_run3_fl boolean not null,
  removed_for_pr_run1_id varchar(8),
  removed_for_pr_run2_id varchar(8),
  removed_for_pr_run3_id varchar(8),
  removed_for_ph_bat_id varchar(8),
  removed_for_ph_bat_fld_cd integer,
  po1_fld_cd integer not null,
  po2_fld_cd integer not null,
  po3_fld_cd integer not null,
  ass1_fld_cd integer not null,
  ass2_fld_cd integer not null,
  ass3_fld_cd integer not null,
  ass4_fld_cd integer not null,
  ass5_fld_cd integer not null,
  event_id integer
);



/*** 2. ejection_ingest table, using ejection_data_2000-2015.csv ***/

create table ejection_ingest (
  game_id varchar(24) not null,
  inn_ct integer not null,
  bat_home_id boolean not null,
  bat_id varchar(8) not null,
  pitch_seq_tx varchar(255),
  event_tx varchar(255) not null,
  ej_code varchar (8) not null,
  ejectee varchar (24) not null,
  job_code varchar (8) not null,
  ump_id varchar(24) not null,
  reason varchar(255) not null
);



/*** 3. event_ejection_stage table, using event_ingest and ejection_ingest tables ***/

create table event_ejection_stage (
  event_uid varchar(255),
  game_id varchar(12) not null,
  game_date date not null,
  game_year integer not null,
  game_month integer not null,
  game_day_of_month integer not null,
  game_number integer not null,
  home_team_id varchar(3) not null,
  away_team_id varchar(3),
  inn_ct integer not null,
  bat_home_id boolean not null,
  half_inning_id varchar(255) not null,
  outs_ct integer,
  balls_ct integer,
  strikes_ct integer,
  pitch_seq_tx varchar(255),
  away_score_ct integer,
  home_score_ct integer,
  runs integer,
  bat_id varchar(8) not null,
  bat_hand_cd hand_cd_type,
  resp_bat_id varchar(8),
  resp_bat_hand_cd hand_cd_type,
  pit_id varchar(8),
  pit_hand_cd hand_cd_type,
  resp_pit_id varchar(8),
  resp_pit_hand_cd hand_cd_type,
  pos2_fld_id varchar(8),
  pos3_fld_id varchar(8),
  pos4_fld_id varchar(8),
  pos5_fld_id varchar(8),
  pos6_fld_id varchar(8),
  pos7_fld_id varchar(8),
  pos8_fld_id varchar(8),
  pos9_fld_id varchar(8),
  base1_run_id varchar(8),
  base2_run_id varchar(8),
  base3_run_id varchar(8),
  event_tx varchar(255) not null,
  leadoff_fl boolean,
  ph_fl boolean,
  bat_fld_cd integer,
  bat_lineup_id integer,
  event_cd integer,
  bat_event_fl boolean,
  ab_fl boolean,
  h_fl integer,
  sh_fl boolean,
  sf_fl boolean,
  event_outs_ct integer,
  dp_fl boolean,
  tp_fl boolean,
  rbi_ct integer,
  wp_fl boolean,
  pb_fl boolean,
  fld_cd integer,
  battedball_cd battedball_cd_type,
  bunt_fl boolean,
  foul_fl boolean,
  battedball_loc_tx varchar(255),
  err_ct integer,
  err1_fld_cd integer,
  err1_cd err_cd_type,
  err2_fld_cd integer,
  err2_cd err_cd_type,
  err3_fld_cd integer,
  err3_cd err_cd_type,
  bat_dest_id integer,
  run1_dest_id integer,
  run2_dest_id integer,
  run3_dest_id integer,
  runs_scored integer,
  bat_play_tx varchar(255),
  run1_play_tx varchar(255),
  run2_play_tx varchar(255),
  run3_play_tx varchar(255),
  run1_sb_fl boolean,
  run2_sb_fl boolean,
  run3_sb_fl boolean,
  run1_cs_fl boolean,
  run2_cs_fl boolean,
  run3_cs_fl boolean,
  run1_pk_fl boolean,
  run2_pk_fl boolean,
  run3_pk_fl boolean,
  run1_resp_pit_id varchar(8),
  run2_resp_pit_id varchar(8),
  run3_resp_pit_id varchar(8),
  game_new_fl boolean,
  game_end_fl boolean,
  pr_run1_fl boolean,
  pr_run2_fl boolean,
  pr_run3_fl boolean,
  removed_for_pr_run1_id varchar(8),
  removed_for_pr_run2_id varchar(8),
  removed_for_pr_run3_id varchar(8),
  removed_for_ph_bat_id varchar(8),
  removed_for_ph_bat_fld_cd integer,
  po1_fld_cd integer,
  po2_fld_cd integer,
  po3_fld_cd integer,
  ass1_fld_cd integer,
  ass2_fld_cd integer,
  ass3_fld_cd integer,
  ass4_fld_cd integer,
  ass5_fld_cd integer,
  event_id integer,
  ej_code varchar(3),
  ejectee varchar(50),
  job_code varchar(2),
  ump_id varchar(50),
  reason varchar(255),
  event_id_new integer,
  event_uid_new varchar(255) 
);


/*** 4. event_final table, using event_ejection_stage ***/

create table event_final (
  event_uid varchar(255) primary key,
  game_id varchar(12) not null,
  game_date date not null,
  game_year integer not null,
  game_month integer not null,
  game_day_of_month integer not null,
  game_number integer not null,
  home_team_id varchar(3) not null,
  away_team_id varchar(3),
  inn_ct integer not null,
  bat_home_id boolean not null,
  half_inning_id varchar(255) not null,
  outs_ct integer,
  balls_ct integer,
  strikes_ct integer,
  pitch_seq_tx varchar(255),
  away_score_ct integer,
  home_score_ct integer,
  runs integer,
  bat_id varchar(8) not null,
  bat_hand_cd hand_cd_type,
  resp_bat_id varchar(8),
  resp_bat_hand_cd hand_cd_type,
  pit_id varchar(8),
  pit_hand_cd hand_cd_type,
  resp_pit_id varchar(8),
  resp_pit_hand_cd hand_cd_type,
  pos2_fld_id varchar(8),
  pos3_fld_id varchar(8),
  pos4_fld_id varchar(8),
  pos5_fld_id varchar(8),
  pos6_fld_id varchar(8),
  pos7_fld_id varchar(8),
  pos8_fld_id varchar(8),
  pos9_fld_id varchar(8),
  base1_run_id varchar(8),
  base2_run_id varchar(8),
  base3_run_id varchar(8),
  event_tx varchar(255) not null,
  leadoff_fl boolean,
  ph_fl boolean,
  bat_fld_cd integer,
  bat_lineup_id integer,
  event_cd integer,
  bat_event_fl boolean,
  ab_fl boolean,
  h_fl integer,
  sh_fl boolean,
  sf_fl boolean,
  event_outs_ct integer,
  dp_fl boolean,
  tp_fl boolean,
  rbi_ct integer,
  wp_fl boolean,
  pb_fl boolean,
  fld_cd integer,
  battedball_cd battedball_cd_type,
  bunt_fl boolean,
  foul_fl boolean,
  battedball_loc_tx varchar(255),
  err_ct integer,
  err1_fld_cd integer,
  err1_cd err_cd_type,
  err2_fld_cd integer,
  err2_cd err_cd_type,
  err3_fld_cd integer,
  err3_cd err_cd_type,
  bat_dest_id integer,
  run1_dest_id integer,
  run2_dest_id integer,
  run3_dest_id integer,
  runs_scored integer,
  bat_play_tx varchar(255),
  run1_play_tx varchar(255),
  run2_play_tx varchar(255),
  run3_play_tx varchar(255),
  run1_sb_fl boolean,
  run2_sb_fl boolean,
  run3_sb_fl boolean,
  run1_cs_fl boolean,
  run2_cs_fl boolean,
  run3_cs_fl boolean,
  run1_pk_fl boolean,
  run2_pk_fl boolean,
  run3_pk_fl boolean,
  run1_resp_pit_id varchar(8),
  run2_resp_pit_id varchar(8),
  run3_resp_pit_id varchar(8),
  game_new_fl boolean,
  game_end_fl boolean,
  pr_run1_fl boolean,
  pr_run2_fl boolean,
  pr_run3_fl boolean,
  removed_for_pr_run1_id varchar(8),
  removed_for_pr_run2_id varchar(8),
  removed_for_pr_run3_id varchar(8),
  removed_for_ph_bat_id varchar(8),
  removed_for_ph_bat_fld_cd integer,
  po1_fld_cd integer,
  po2_fld_cd integer,
  po3_fld_cd integer,
  ass1_fld_cd integer,
  ass2_fld_cd integer,
  ass3_fld_cd integer,
  ass4_fld_cd integer,
  ass5_fld_cd integer,
  event_id integer,
  ej_code varchar(3),
  ejectee varchar(50),
  job_code varchar(2),
  ump_id varchar(50),
  reason varchar(255)
);

