drop table if exists fields;
drop table if exists event_cd_desc;
drop table if exists event_ingest;
drop table if exists event;

create type hand_cd_type as enum('L', 'R');
create type battedball_cd_type as enum('F', 'L', 'P', 'G');
create type err_cd_type as enum('F', 'D', 'N', 'T');

create table fields (
  field_number integer not null,
  description varchar(43) not null,
  header varchar(25) not null
);

create table event_cd_desc (
  event_cd integer not null,
  description varchar(255) not null,
  abbreviation varchar(4) not null
);

create table event_ingest (
  game_id varchar,
  away_team_id varchar,
  inn_ct varchar,
  bat_home_id varchar,
  outs_ct varchar,
  balls_ct varchar,
  strikes_ct varchar,
  pitch_seq_tx varchar,
  away_score_ct varchar,
  home_score_ct varchar,
  bat_id varchar,
  bat_hand_cd varchar,
  resp_bat_id varchar,
  resp_bat_hand_cd varchar,
  pit_id varchar,
  pit_hand_cd varchar,
  resp_pit_id varchar,
  resp_pit_hand_cd varchar,
  pos2_fld_id varchar,
  pos3_fld_id varchar,
  pos4_fld_id varchar,
  pos5_fld_id varchar,
  pos6_fld_id varchar,
  pos7_fld_id varchar,
  pos8_fld_id varchar,
  pos9_fld_id varchar,
  base1_run_id varchar,
  base2_run_id varchar,
  base3_run_id varchar,
  event_tx varchar,
  leadoff_fl varchar,
  ph_fl varchar,
  bat_fld_cd varchar,
  bat_lineup_id varchar,
  event_cd varchar,
  bat_event_fl varchar,
  ab_fl varchar,
  h_fl varchar,
  sh_fl varchar,
  sf_fl varchar,
  event_outs_ct varchar,
  dp_fl varchar,
  tp_fl varchar,
  rbi_ct varchar,
  wp_fl varchar,
  pb_fl varchar,
  fld_cd varchar,
  battedball_cd varchar,
  bunt_fl varchar,
  foul_fl varchar,
  battedball_loc_tx varchar,
  err_ct varchar,
  err1_fld_cd varchar,
  err1_cd varchar,
  err2_fld_cd varchar,
  err2_cd varchar,
  err3_fld_cd varchar,
  err3_cd varchar,
  bat_dest_id varchar,
  run1_dest_id varchar,
  run2_dest_id varchar,
  run3_dest_id varchar,
  bat_play_tx varchar,
  run1_play_tx varchar,
  run2_play_tx varchar,
  run3_play_tx varchar,
  run1_sb_fl varchar,
  run2_sb_fl varchar,
  run3_sb_fl varchar,
  run1_cs_fl varchar,
  run2_cs_fl varchar,
  run3_cs_fl varchar,
  run1_pk_fl varchar,
  run2_pk_fl varchar,
  run3_pk_fl varchar,
  run1_resp_pit_id varchar,
  run2_resp_pit_id varchar,
  run3_resp_pit_id varchar,
  game_new_fl varchar,
  game_end_fl varchar,
  pr_run1_fl varchar,
  pr_run2_fl varchar,
  pr_run3_fl varchar,
  removed_for_pr_run1_id varchar,
  removed_for_pr_run2_id varchar,
  removed_for_pr_run3_id varchar,
  removed_for_ph_bat_id varchar,
  removed_for_ph_bat_fld_cd varchar,
  po1_fld_cd varchar,
  po2_fld_cd varchar,
  po3_fld_cd varchar,
  ass1_fld_cd varchar,
  ass2_fld_cd varchar,
  ass3_fld_cd varchar,
  ass4_fld_cd varchar,
  ass5_fld_cd varchar,
  event_id varchar
);

create table event (
  event_uid varchar(15) primary key,
  game_id varchar(12) not null,
  game_date date not null,
  game_year integer not null,
  game_month integer not null,
  game_day_of_month integer not null,
  game_number integer not null,
  home_team_id varchar(3) not null,
  away_team_id varchar(3) not null,
  inn_ct integer not null,
  bat_home_id boolean not null,
  half_inning_id varchar(15) not null,
  outs_ct integer not null,
  balls_ct integer not null,
  strikes_ct integer not null,
  pitch_seq_tx varchar(255),
  away_score_ct integer not null,
  home_score_ct integer not null,
  runs integer not null,
  bat_id varchar(8) not null,
  bat_hand_cd hand_cd_type,
  resp_bat_id varchar(8) not null,
  resp_bat_hand_cd hand_cd_type,
  pit_id varchar(8) not null,
  pit_hand_cd hand_cd_type not null,
  resp_pit_id varchar(8) not null,
  resp_pit_hand_cd hand_cd_type not null,
  pos2_fld_id varchar(8) not null,
  pos3_fld_id varchar(8) not null,
  pos4_fld_id varchar(8) not null,
  pos5_fld_id varchar(8) not null,
  pos6_fld_id varchar(8) not null,
  pos7_fld_id varchar(8) not null,
  pos8_fld_id varchar(8) not null,
  pos9_fld_id varchar(8) not null,
  base1_run_id varchar(8),
  base2_run_id varchar(8),
  base3_run_id varchar(8),
  event_tx varchar(255) not null,
  leadoff_fl boolean not null,
  ph_fl boolean not null,
  bat_fld_cd integer not null,
  bat_lineup_id integer not null,
  event_cd integer not null,
  bat_event_fl boolean not null,
  ab_fl boolean not null,
  h_fl integer not null,
  sh_fl boolean not null,
  sf_fl boolean not null,
  event_outs_ct integer not null,
  dp_fl boolean not null,
  tp_fl boolean not null,
  rbi_ct integer not null,
  wp_fl boolean not null,
  pb_fl boolean not null,
  fld_cd integer not null,
  battedball_cd battedball_cd_type,
  bunt_fl boolean not null,
  foul_fl boolean not null,
  battedball_loc_tx varchar(255),
  err_ct integer not null,
  err1_fld_cd integer not null,
  err1_cd err_cd_type not null,
  err2_fld_cd integer not null,
  err2_cd err_cd_type not null,
  err3_fld_cd integer not null,
  err3_cd err_cd_type not null,
  bat_dest_id integer not null,
  run1_dest_id integer not null,
  run2_dest_id integer not null,
  run3_dest_id integer not null,
  runs_scored integer not null,
  bat_play_tx varchar(255),
  run1_play_tx varchar(255),
  run2_play_tx varchar(255),
  run3_play_tx varchar(255),
  run1_sb_fl boolean not null,
  run2_sb_fl boolean not null,
  run3_sb_fl boolean not null,
  run1_cs_fl boolean not null,
  run2_cs_fl boolean not null,
  run3_cs_fl boolean not null,
  run1_pk_fl boolean not null,
  run2_pk_fl boolean not null,
  run3_pk_fl boolean not null,
  run1_resp_pit_id varchar(8),
  run2_resp_pit_id varchar(8),
  run3_resp_pit_id varchar(8),
  game_new_fl boolean not null,
  game_end_fl boolean not null,
  pr_run1_fl boolean not null,
  pr_run2_fl boolean not null,
  pr_run3_fl boolean not null,
  removed_for_pr_run1_id varchar(8),
  removed_for_pr_run2_id varchar(8),
  removed_for_pr_run3_id varchar(8),
  removed_for_ph_bat_id varchar(8),
  removed_for_ph_bat_fld_cd integer,
  po1_fld_cd integer not null,
  po2_fld_cd integer not null,
  po3_fld_cd integer not null,
  ass1_fld_cd integer not null,
  ass2_fld_cd integer not null,
  ass3_fld_cd integer not null,
  ass4_fld_cd integer not null,
  ass5_fld_cd integer not null,
  event_id integer
);

create index event_game_year_index on event(game_year);
create index event_game_half_inning_index on event(half_inning_id);
