insert into event_cd_desc values
  ( 0, 'unknown event', 'unkn'),
  ( 1, 'no event', 'none'),
  ( 2, 'generic out', 'out'),
  ( 3, 'strikeout', 'k'),
  ( 4, 'stolen base', 'sb'),
  ( 5, 'defensive indifference', 'di'),
  ( 6, 'caught stealing', 'cs'),
  ( 7, 'pickoff error', 'pke'),
  ( 8, 'pickoff', 'pk'),
  ( 9, 'wild pitch', 'wp'),
  (10, 'passed ball', 'pb'),
  (11, 'balk', 'bk'),
  (12, 'other advance', 'oa'),
  (13, 'foul error', 'fe'),
  (14, 'walk', 'bb'),
  (15, 'intentional walk', 'ibb'),
  (16, 'hit by pitch', 'hbp'),
  (17, 'interference', 'intr'),
  (18, 'error', 'e'),
  (19, 'fielders choice', 'fc'),
  (20, 'single', '1b'),
  (21, 'double', '2b'),
  (22, 'triple', '3b'),
  (23, 'home run', 'hr'),
  (24, 'missing play', 'miss')
;
